#!/bin/sh

PROGRAMNAME=$(basename $0)
HELP_MSG="You can get help by specifying '$PROGRAMNAME -h'"

# ヘルプメッセージ関数
usage() {
  echo "Usage: $0 [-opt] file1 file2 ..."
  echo 
  echo "Options:"
  echo "  -h, --help"
  echo "  -v, --version"
  echo
  exit 1
}

# 準備関数
prepare() {
  javac -encoding UTF-8 ${GRASSLANG_DIR}/Grass.java
}

# 実行関数
run() {
  java -classpath ${GRASSLANG_DIR} Grass $1
}

params=()

# オプション解析
for OPT in "$@"
do
  case "$OPT" in
    # ヘルプメッセージ
    '-h'|'--help' )
      usage
      exit 1
      ;;
    # バージョンメッセージ
    '-v'|'--version' )
      echo "grass version $VERSION"
      exit 1
      ;;
    # 「-」か「--」だけ打った時
    '--'|'-' )
      shift 1
      params+=("$@")
      break
      ;;
    -* )
      echo "$PROGRAMNAME: 「$(echo $1 | sed 's/^-*//')」option does not exist. Please check with '$PROGRAMNAME -h'." 1>&2
      exit 1
      ;;
    * )
      # コマンド引数（オプション以外のパラメータ）
      if [[ ! -z "$1" ]] && [[ ! "$1" =~ ^-+ ]]; then
        params+=("$1")
        shift 1
      fi
      ;;
  esac
done

# 実行部分
for param in "$params"
do
  if [ ! ${param##*.} = grass ]; then
    echo "Specify a Grass file as the file to be executed."
    exit 1
  fi
done

prepare

for param in "$params"
do
  run $param
done
